import {useState} from 'react';
import {UserPlus, Target, TrendingUp, CheckCircle2, Pencil, Trash2, RotateCcw, CalendarDays, Search} from 'lucide-react';
import Modal from './Modal';
import {parseBRL,formatBRL} from '../lib/currency';

const statusOptions=[['prospecting','Novo lead'],['negotiation','Em negociação'],['proposal','Proposta enviada'],['closed_won','Convertido'],['closed_lost','Perdido']];
const labels=Object.fromEntries(statusOptions);
const active=p=>!['closed_won','closed_lost'].includes(p.status);
const today=()=>new Date().toLocaleDateString('en-CA');
const currentMonth=()=>today().slice(0,7);
const defaultForm=()=>({client_name:'',expected_amount:'',expected_date:today(),probability:'100',status:'prospecting',notes:'',profile_id:''});
const pct=(a,b)=>b>0?Math.round(a/b*100):0;
export default function LeadsView({projections,profiles,selectedProfile,onSave,onDelete}){
  const [month,setMonth]=useState(currentMonth());
  const [filter,setFilter]=useState('active');
  const [search,setSearch]=useState('');
  const [open,setOpen]=useState(false);
  const [editing,setEditing]=useState(null);
  const [form,setForm]=useState(defaultForm());
  const leads=projections.filter(p=>p.is_lead);
  const ongoing=leads.filter(active);
  const inMonth=ongoing.filter(p=>String(p.expected_date||'').slice(0,7)===month);
  const gross=inMonth.reduce((a,p)=>a+Number(p.expected_amount||0),0);
  const weighted=gross;
  const converted=leads.filter(p=>p.status==='closed_won').length;
  const concluded=leads.filter(p=>['closed_won','closed_lost'].includes(p.status)).length;
  const shown=leads.filter(p=>(filter==='active'?active(p):filter==='won'?p.status==='closed_won':p.status==='closed_lost')&&String(p.client_name||'').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>String(a.expected_date).localeCompare(String(b.expected_date)));
  const launch=p=>{setEditing(p?.id||null);setForm(p?{...p,expected_amount:String(p.expected_amount),probability:'100'}:{...defaultForm(),profile_id:selectedProfile?.id||profiles[0]?.id||''});setOpen(true)};
  const save=e=>{e.preventDefault();const value=parseBRL(form.expected_amount),chance=100;
    if(!form.client_name.trim()||!form.profile_id||!form.expected_date||!Number.isFinite(value)||value<=0){alert('Preencha nome, consultor, data, valor válido.');return;}
    onSave({...form,client_name:form.client_name.trim(),client_id:null,expected_amount:value,probability:chance,is_lead:true},editing);setOpen(false);
  };
  const input='mt-1 w-full rounded-xl border border-white/10 bg-slate-800 p-3 text-white outline-none focus:border-blue-400/50';
  return <section className="space-y-6">
    <div className="relative overflow-hidden rounded-3xl border border-blue-400/15 bg-gradient-to-br from-[#142d56] via-[#111e34] to-[#0b1323] p-6 sm:p-8">
      <div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full bg-blue-500/10 blur-3xl"/>
      <div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-blue-300"><UserPlus size={16}/> Inteligência comercial</div><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Projeção de Leads</h2><p className="mt-2 text-sm text-slate-300">Visualize oportunidades futuras sem misturá-las com vendas realizadas.</p></div><label className="flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2"><CalendarDays size={16}/><input aria-label="Mês de previsão" type="month" value={month} onChange={e=>setMonth(e.target.value)} className="bg-transparent text-sm outline-none [color-scheme:dark]"/></label></div>
      <div className="relative mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><p className="text-xs uppercase tracking-widest text-slate-400">Potencial de leads no mês</p><div className="mt-3 text-3xl font-bold">{formatBRL(gross)}</div><p className="mt-2 text-xs text-slate-400">Soma das oportunidades abertas previstas para o período</p></div><div className="rounded-2xl border border-cyan-400/15 bg-cyan-400/[.06] p-5"><p className="text-xs uppercase tracking-widest text-cyan-200">Projeção integral · 100%</p><div className="mt-3 text-3xl font-bold text-cyan-100">{formatBRL(weighted)}</div><p className="mt-2 text-xs text-slate-400">Valor integral das oportunidades (chance fixa de 100%)</p></div></div>
    </div>
    <div className="grid gap-3 sm:grid-cols-3">{[{label:'Leads em andamento',value:ongoing.length,icon:UserPlus,detail:'Oportunidades abertas'},{label:'Convertidos',value:converted,icon:CheckCircle2,detail:'Status convertido (não gera venda)'},{label:'Taxa de conversão',value:concluded?`${pct(converted,concluded)}%`:'—',icon:TrendingUp,detail:'Convertidos / leads encerrados'}].map(x=><div key={x.label} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex items-center justify-between text-sm text-slate-400"><span>{x.label}</span><x.icon size={18} className="text-blue-300"/></div><p className="mt-4 text-3xl font-bold">{x.value}</p><p className="mt-1 text-xs text-slate-500">{x.detail}</p></div>)}</div>
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#111b2b]/75"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 p-5 sm:px-6"><div><h3 className="text-lg font-bold">Pipeline de leads</h3><p className="mt-1 text-xs text-slate-400">Cadastre, atualize e acompanhe cada oportunidade.</p></div><button onClick={()=>launch(null)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold hover:bg-blue-500"><UserPlus size={17}/> Novo lead</button></div>
      <div className="flex flex-wrap gap-2 p-5 pb-2 sm:px-6">{[['active','Em andamento'],['won','Convertidos'],['lost','Perdidos']].map(([k,v])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-lg px-3 py-2 text-sm ${filter===k?'bg-blue-600 text-white':'bg-white/5 text-slate-400 hover:bg-white/10'}`}>{v}</button>)}<div className="relative ml-auto"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lead..." className="w-48 rounded-lg border border-white/10 bg-slate-800 py-2 pl-9 pr-3 text-sm outline-none"/></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-white/10 text-slate-400"><tr>{['Lead','Responsável','Valor potencial','Previsão','Chance','Etapa','Ações'].map(t=><th key={t} className="px-5 py-3 font-medium">{t}</th>)}</tr></thead><tbody>{shown.map(p=><tr key={p.id} className="border-t border-white/5 hover:bg-white/[.025]"><td className="px-5 py-4"><div className="font-semibold">{p.client_name}</div>{p.notes&&<div className="mt-1 max-w-[220px] truncate text-xs text-slate-500" title={p.notes}>{p.notes}</div>}</td><td className="px-5 py-4 text-slate-300">{profiles.find(x=>x.id===p.profile_id)?.name||'—'}</td><td className="px-5 py-4 font-semibold text-cyan-200">{formatBRL(p.expected_amount)}</td><td className="px-5 py-4 text-slate-300">{p.expected_date||'—'}</td><td className="px-5 py-4">100%</td><td className="px-5 py-4"><span className="rounded-lg bg-blue-400/10 px-2 py-1 text-xs text-blue-200">{labels[p.status]||p.status}</span></td><td className="px-5 py-4"><div className="flex gap-1"><button title="Editar" onClick={()=>launch(p)} className="rounded-lg p-2 text-blue-300 hover:bg-white/10"><Pencil size={17}/></button>{!active(p)&&<button title="Reabrir" onClick={()=>onSave({...p,status:'prospecting'},p.id)} className="rounded-lg p-2 text-emerald-300 hover:bg-white/10"><RotateCcw size={17}/></button>}<button title="Excluir" onClick={()=>{if(confirm(`Excluir lead ${p.client_name}?`))onDelete(p.id)}} className="rounded-lg p-2 text-rose-300 hover:bg-white/10"><Trash2 size={17}/></button></div></td></tr>)}{!shown.length&&<tr><td colSpan="7" className="px-5 py-10 text-center text-slate-500">Nenhum lead encontrado neste filtro.</td></tr>}</tbody></table></div>
    </div>
    <p className="text-xs text-slate-500">Marcar um lead como convertido apenas encerra sua projeção. Para registrar faturamento, cadastre o cliente e lance a venda na Carteira de Clientes.</p>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Editar lead':'Novo lead'}><form onSubmit={save} className="space-y-4"><label className="block text-sm text-slate-300">Nome do lead *<input required value={form.client_name} onChange={e=>setForm(f=>({...f,client_name:e.target.value}))} className={input}/></label><label className="block text-sm text-slate-300">Consultor responsável *<select required value={form.profile_id} onChange={e=>setForm(f=>({...f,profile_id:e.target.value}))} disabled={!!selectedProfile} className={input}>{profiles.filter(p=>!selectedProfile||p.id===selectedProfile.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Valor potencial (R$) *<input required inputMode="decimal" placeholder="2.000,50" value={form.expected_amount} onChange={e=>setForm(f=>({...f,expected_amount:e.target.value}))} className={input}/></label><label className="text-sm text-slate-300">Previsão *<input required type="date" value={form.expected_date} onChange={e=>setForm(f=>({...f,expected_date:e.target.value}))} className={input}/></label><label className="text-sm text-slate-300">Probabilidade (%)<div className="mt-1 rounded-xl border border-blue-400/20 bg-blue-500/10 p-3 font-semibold text-blue-200">100% · fixo</div></label><label className="text-sm text-slate-300">Etapa<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))} className={input}>{statusOptions.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><label className="block text-sm text-slate-300">Observações<textarea rows="3" value={form.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} className={input}/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg bg-white/10 px-4 py-2">Cancelar</button><button type="submit" className="rounded-lg bg-blue-600 px-5 py-2 font-semibold">Salvar lead</button></div></form></Modal>
  </section>;
}
